import type { Project } from "./types";

export const projectItems: Project[] = [
  {
    slug: "skyline-business-centre",
    title: "Skyline Business Centre",
    location: "Toshkent - Mirobod",
    year: "2026",
    status: "Sotuvda",
    klass: "Business",
    type: "Business",
    area: "40 qavat - 52 000 m2",
    image: "/hero/1.png",
    desc: "Markaziy lokatsiya, premium fasad, kuchli logistika va servis infratuzilmasi.",
    highlights: ["Markaziy lokatsiya", "Premium lobby", "Smart parking"],
  },
  {
    slug: "aurora-residence",
    title: "Aurora Residence",
    location: "Toshkent - Yakkasaroy",
    year: "2027",
    status: "Qurilishda",
    klass: "Premium",
    type: "Residential",
    area: "7 blok - 31 000 m2",
    image: "/hero/2.png",
    desc: "Sokin kvartal, material palitrasi, foydali reja va yashil hudud.",
    highlights: ["Landshaft hovli", "Family layout", "Shovqinsiz kvartal"],
  },
  {
    slug: "stonepark",
    title: "StonePark",
    location: "Toshkent - Yunusobod",
    year: "2024",
    status: "Topshirilgan",
    klass: "Comfort",
    type: "Residential",
    area: "5 blok - 24 000 m2",
    image: "/hero/3.png",
    desc: "Oilaviy makon: maktab, bogcha, servis va sport zonalari.",
    highlights: ["Maktab va bogcha", "Yashil hudud", "Sport zonasi"],
  },
  {
    slug: "nexus-tower",
    title: "Nexus Tower",
    location: "Toshkent - Shayxontohur",
    year: "2026",
    status: "Sotuvda",
    klass: "Premium",
    type: "Mixed",
    area: "32 qavat - 44 000 m2",
    image: "/hero/4.png",
    desc: "Mixed-use: retail, office va apartments yagona konseptda.",
    highlights: ["Mixed-use model", "A-class office", "Retail podium"],
  },
  {
    slug: "riverline",
    title: "Riverline",
    location: "Toshkent - Sergeli",
    year: "2027",
    status: "Qurilishda",
    klass: "Business",
    type: "Residential",
    area: "9 blok - 36 000 m2",
    image: "/hero/5.png",
    desc: "Reja mantiqi, quyosh tushishi, tashqi hudud va transport qulayligi.",
    highlights: ["Transit yaqin", "Quyosh orientatsiyasi", "Yurish yo'laklari"],
  },
  {
    slug: "atlas",
    title: "Atlas",
    location: "Toshkent - Mirzo Ulugbek",
    year: "2026",
    status: "Sotuvda",
    klass: "Comfort",
    type: "Residential",
    area: "6 blok - 28 000 m2",
    image: "/hero/6.png",
    desc: "Kundalik hayot uchun servislar, park yo'laklari va oilaviy zonalar.",
    highlights: ["Servis ichki hudud", "Bolalar zonasi", "Park integratsiyasi"],
  },
  {
    slug: "zenith-plaza",
    title: "Zenith Plaza",
    location: "Toshkent - Chilonzor",
    year: "2025",
    status: "Topshirilgan",
    klass: "Business",
    type: "Business",
    area: "18 qavat - 21 000 m2",
    image: "/hero/1.png",
    desc: "Biznes oqimlari, parking logikasi va energiya samaradorligi.",
    highlights: ["Energy efficiency", "Flexible office", "Fast access"],
  },
  {
    slug: "silk-avenue",
    title: "Silk Avenue",
    location: "Toshkent - Olmazor",
    year: "2027",
    status: "Qurilishda",
    klass: "Premium",
    type: "Mixed",
    area: "Retail + living - 39 000 m2",
    image: "/hero/2.png",
    desc: "Premium retail, yashash hududi va landshaft yagona dizayn tilida.",
    highlights: ["Premium retail", "Public plaza", "Iconic facade"],
  },
];
